# Generated by Django 4.2.2 on 2023-07-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-posted_time'],
            },
        ),
    ]
