# Generated by Django 4.2.2 on 2023-07-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0002_company_department_delete_skill_company_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='company_banners'),
        ),
    ]
