# Generated by Django 4.2.2 on 2023-07-15 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0023_alter_user_skills'),
        ('Employer', '0007_remove_company_related_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shortlisted', models.BooleanField(default=False)),
                ('is_interviewed', models.BooleanField(default=False)),
                ('is_informed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JobResponsibilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='banner',
            field=models.ImageField(blank=True, default='', upload_to='company_banners'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='company_logos'),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('job_type', models.CharField(choices=[('WFH', 'WFH'), ('Full-time', 'Full-time'), ('Hybrid', 'Hybrid')], max_length=100)),
                ('is_closed', models.BooleanField(default=False)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('applicants', models.ManyToManyField(to='Employer.applicant')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.company')),
                ('requirements', models.ManyToManyField(to='Employer.jobrequirements')),
                ('responsibilities', models.ManyToManyField(to='Employer.jobresponsibilities')),
                ('skills_required', models.ManyToManyField(to='User.skill')),
            ],
        ),
        migrations.CreateModel(
            name='RejectedApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
    ]
