# Generated by Django 4.2.2 on 2023-07-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0008_applicant_jobrequirements_jobresponsibilities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('answer_is_yes', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='applicants',
            field=models.ManyToManyField(blank=True, to='Employer.applicant'),
        ),
        migrations.AddField(
            model_name='job',
            name='questions',
            field=models.ManyToManyField(to='Employer.jobquestions'),
        ),
    ]
