# Generated by Django 4.2.2 on 2023-07-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0009_jobquestions_alter_job_applicants_job_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='resume',
            field=models.FileField(default='', upload_to='resumes'),
            preserve_default=False,
        ),
    ]
