# Generated by Django 4.2.2 on 2023-07-18 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0010_applicant_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='applied_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
