# Generated by Django 4.2.2 on 2023-07-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0011_applicant_applied_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
