# Generated by Django 4.2.2 on 2023-07-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0013_applicant_interview_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='about',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
