# Generated by Django 4.2.2 on 2023-07-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0015_job_job_time_alter_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expected_salary',
            field=models.PositiveBigIntegerField(default=24000),
            preserve_default=False,
        ),
    ]
