# Generated by Django 4.2.2 on 2023-07-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0016_job_expected_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='interview_date',
            field=models.DateField(default='2023-04-27'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='interview_time',
            field=models.CharField(default='8:00 am', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('On-Site', 'On-Site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=100),
        ),
    ]
