# Generated by Django 4.2.2 on 2023-07-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0017_applicant_interview_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='interview_date',
            field=models.CharField(max_length=100),
        ),
    ]
