# Generated by Django 4.2.2 on 2023-07-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
