# Generated by Django 4.2.2 on 2023-07-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_delay',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_limit',
            field=models.IntegerField(default=1),
        ),
    ]
