# Generated by Django 4.2.2 on 2023-07-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_alter_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='info',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
