# Generated by Django 4.2.2 on 2023-07-11 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_user_skills_project_connections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='education',
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('user', 'name')},
        ),
    ]
