# Generated by Django 4.2.2 on 2023-07-14 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0007_remove_company_related_users'),
        ('User', '0021_skill_alter_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employer.company'),
        ),
    ]
