# Generated by Django 4.2.2 on 2023-07-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_alter_user_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
