# Generated by Django 4.2.2 on 2023-07-18 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0024_alter_skill_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connections',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='connections',
            name='follower',
        ),
        migrations.AddField(
            model_name='connections',
            name='follower',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
