# Generated by Django 4.2.2 on 2023-07-20 03:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0025_alter_connections_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connections',
            name='follower',
        ),
        migrations.AddField(
            model_name='connections',
            name='following',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
