# Generated by Django 4.2.2 on 2023-07-20 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0011_applicant_applied_on'),
        ('User', '0026_remove_connections_follower_connections_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=200)),
                ('graduated_year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('year_from', models.IntegerField()),
                ('year_to', models.IntegerField()),
                ('still_working', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_company', to='Employer.company')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.ManyToManyField(blank=True, to='User.education'),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.ManyToManyField(blank=True, to='User.experience'),
        ),
    ]
