# Generated by Django 4.2.2 on 2023-07-20 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0030_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
