# Generated by Django 4.2.2 on 2023-07-20 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0031_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('link_thread', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Post', 'Post'), ('Job', 'Job'), ('Connection', 'Connection')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rel_img', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
