# Generated by Django 4.2.2 on 2023-07-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0033_user_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='content',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
