# Generated by Django 4.2.2 on 2023-07-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0034_report_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedposts',
            name='post',
        ),
        migrations.AddField(
            model_name='savedposts',
            name='post',
            field=models.ManyToManyField(to='User.post'),
        ),
    ]
