# Generated by Django 4.2.2 on 2023-08-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0035_remove_savedposts_post_savedposts_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, upload_to='resume'),
        ),
    ]
