# Generated by Django 4.2.2 on 2023-08-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0036_user_is_premium_user_user_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(null=True, upload_to='resume'),
        ),
    ]
