# Generated by Django 4.2.2 on 2023-08-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0037_alter_user_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium_end_date',
            field=models.DateTimeField(default='2023-08-02'),
            preserve_default=False,
        ),
    ]
