# Generated by Django 4.2.2 on 2023-08-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0038_user_premium_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='premium_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
